FROM flink:1.18.0-scala_2.12-java11

USER root
RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/flink
COPY target/environment-simulator-java-1.0-SNAPSHOT.jar /opt/flink/usrlib/environment-simulator-java-1.0-SNAPSHOT.jar